[build]
  functions = "functions"
  publish = "."
  command = "node scripts/generate-audio.js"

[functions]
  node_bundler = "esbuild"

[dev]
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200 